# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

  
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
  
rules:
  no-console: 0
  import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version
